const PI = Math.PI; 
// user configs

export let defaults = {
	amplitude: {val: .5, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	period: {val: .5, min: .005, max: 1.005, step: .005, name: 'Period', jitter: .5},
	phaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	verticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	sineAmplitude: {val: .5, min: -20, max: 20, step: .1, name: 'Amplitude', jitter: .8},
	sinePeriod: {val: .5, min: .005, max: 1, step: .005, name: 'Period', jitter: .5},
	sinePhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	sineVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	sqrAmplitude: {val: .5, min: -10, max: 10, step: .1, name: 'Amplitude', jitter: .8},
	sqrPeriod: {val: .5, min: .005, max: 1, step: .005, name: 'Period', jitter: .5},
	sqrPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	sqrVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	sqrN: {val: 21, min: 1, max: 1000, step: 1, name: 'N (Σ Upper Bound', jitter: .75},
	triAmplitude: {val: .5, min: -10, max: 10, step: .1, name: 'Amplitude', jitter: .8},
	triPeriod: {val: .5, min: .005, max: 1, step: .005, name: 'Period', jitter: .5},
	triPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	triVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	triN: {val: 21, min: 1, max: 1000, step: 1, name: 'N (Σ Upper Bound', jitter: .1},
	sawAmplitude: {val: .5, min: -10, max: 10, step: .1, name: 'Amplitude', jitter: .8},
	sawPeriod: {val: .5, min: .005, max: 1, step: .005, name: 'Period', jitter: .5},
	sawPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	sawVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	sawN: {val: 21, min: 1, max: 1000, step: 1, name: 'N (Σ Upper Bound', jitter: .1},
	simAmplitude: {val: .5, min: -20, max: 20, step: .1, name: 'Amplitude', jitter: .8},
	simPeriod: {val: .5, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	simPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	simVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	simY: {val: 500, min: 0, max: 10000, step: 100, name: 'y-Value', jitter: .8},
	signSimThreshold: {val: 0, min: -1, max: 1, step: .1, name: 'Threshold', jitter: .9},
	plsAmplitude: {val: .5, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	plsPeriod: {val: .5, min: .005, max: 1.005, step: .005, name: 'Period', jitter: .5},
	plsPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	plsVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	plsN: {val: 21, min: 1, max: 1000, step: 1, name: 'N (Σ Upper Bound', jitter: .1},
	plsRatio: {val: .25, min: -2, max: 2, step: .01, name: 'Ratio τ/T', jitter: .25},
	dmpSineAmplitude: {val: .5, min: -20, max: 20, step: .1, name: 'Amplitude', jitter: .8},
	dmpSinePeriod: {val: .125, min: .005, max: 1, step: .005, name: 'Period', jitter: .5},
	dmpSinePhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	dmpSineVerticalShift: {val: .5, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	dmpSineDecay: {val: 5, min: -20, max: 20, step: .1, name: 'Decay Constant', jitter: .5},
	
	easeNoneAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeNonePeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeNonePhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeNoneVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeLinearAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeLinearPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeLinearPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeLinearVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easePolyInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easePolyInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easePolyInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easePolyInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easePolyInExponent: {val: 3, min: 1, max: 10, step: 1, name: 'Polynomial Exponent', jitter: .75},
	easePolyOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easePolyOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easePolyOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easePolyOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easePolyOutExponent: {val: 3, min: 1, max: 10, step: 1, name: 'Polynomial Exponent', jitter: .75},
	easePolyInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easePolyInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easePolyInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easePolyInOutVerticalShift: {val: 1, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easePolyInOutExponent: {val: 3, min: 1, max: 10, step: 1, name: 'Polynomial Exponent', jitter: .75},
	easeSinInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeSinInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeSinInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeSinInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeSinOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeSinOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeSinOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeSinOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeSinInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeSinInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeSinInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeSinInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeExpInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeExpInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeExpInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeExpInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeExpOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeExpOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeExpOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeExpOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeExpInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeExpInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeExpInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeExpInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeCircleInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeCircleInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeCircleInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeCircleInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeCircleOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeCircleOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeCircleOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeCircleOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeCircleInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeCircleInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeCircleInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeCircleInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBounceInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBounceInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBounceInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBounceInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBounceOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBounceOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBounceOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBounceOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBounceInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBounceInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBounceInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBounceInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBackInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBackInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBackInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBackInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBackInOvershoot: {val: 1.7, min: 1, max: 10, step: .05, name: 'Back Overshoot', jitter: .75},
	easeBackOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBackOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBackOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBackOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBackOutOvershoot: {val: 1.7, min: 1, max: 10, step: .05, name: 'Back Overshoot', jitter: .75},
	easeBackInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeBackInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeBackInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeBackInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeBackInOutOvershoot: {val: 1.7, min: 1, max: 10, step: .05, name: 'Back Overshoot', jitter: .75},
	easeElasticInAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeElasticInPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeElasticInPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeElasticInVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeElasticInInnerAmplitude: {val: 1, min: 0, max: 5, step: .05, name: 'Elastic Amplitude', jitter: .75},
	easeElasticInInnerPeriod: {val: .3, min: 0, max: 5, step: .05, name: 'Elastic Period', jitter: .75},
	easeElasticOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeElasticOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeElasticOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeElasticOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeElasticOutInnerAmplitude: {val: 1, min: 0, max: 5, step: .05, name: 'Elastic Amplitude', jitter: .75},
	easeElasticOutInnerPeriod: {val: .3, min: 0, max: 5, step: .05, name: 'Elastic Period', jitter: .75},
	easeElasticInOutAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeElasticInOutPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeElasticInOutPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeElasticInOutVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeElasticInOutInnerAmplitude: {val: 1, min: 0, max: 5, step: .05, name: 'Elastic Amplitude', jitter: .75},
	easeElasticInOutInnerPeriod: {val: .3, min: 0, max: 5, step: .05, name: 'Elastic Period', jitter: .75},
	easeStepAmplitude: {val: 1, min: -4, max: 4, step: .1, name: 'Amplitude', jitter: .8},
	easeStepPeriod: {val: 1, min: .005, max: 2, step: .005, name: 'Period', jitter: .5},
	easeStepPhaseShift: {val: 0, min: -1, max: 1, step: .01, name: 'Phase-Shift (1=2π)', jitter: .5},
	easeStepVerticalShift: {val: 0, min: -10, max: 10, step: .1, name: 'Vertical-Shift', jitter: .5},
	easeStepN: {val: 8, min: 1, max: 100, step: 1, name: 'Number of Intervals', jitter: .5},
	easeStepStepIncline: {val: 0, min: -1, max: 1, step: .05, name: 'Step Incline', jitter: .5},

	alphaType: 'SineWave',
	omegaType: 'SineWave',

	nBands: {val: 17, min: 1, max: 100, step: 1, name: 'Number of Bands', jitter: .5},
	initialBandHeight: {val: .8, min: 0, max: 4.05, step: .05, name: 'Body Height', jitter: .5},
	initialGapHeight: {val: .4, min: .05, max: 4.05, step: .05, name: 'Gap Height', jitter: .5},
	bandEaseType: 'EaseNoneWave',
	gapEaseType: 'EaseNoneWave',

	domainXInc: {val: .003, min: .001, max: 1.00, step: .001, name: 'X-Increment', jitter: .05},
	domainX0: {val: 0, min: -8, max: 8, step: .1, name: 'Left', jitter: .25},
	domainX1: {val: 1, min: -8, max: 8, step: .1, name: 'Right', jitter: .25},
	domainY0: {val: 0, min: -4, max: 4, step: .1, name: 'Top', jitter: .25},
	domainY1: {val: 1, min: -4, max: 4, step: .1, name: 'Bottom', jitter: .25},
	
	rangeX0: {val: 0, min: -1920, max: 1920, step: 20, name: 'Left', jitter: .25},
	rangeX1: {val: 720, min: -1920, max: 1920, step: 20, name: 'Right', jitter: .25},
	rangeY0: {val: 0, min: -1080, max: 1080, step: 20, name: 'Top', jitter: .25},
	rangeY1: {val: 40, min: -1080, max: 1080, step: 20, name: 'Bottom', jitter: .25},
	
	designX0: {val: 0, min: 0, max: 1920, step: 20, name: 'Left', jitter: .25},
	designX1: {val: 720, min: 0, max: 1920, step: 20, name: 'Right', jitter: .25},
	designY0: {val: 0, min: 0, max: 1080, step: 20, name: 'Top', jitter: .25},
	designY1: {val: 720, min: 0, max: 1080, step: 20, name: 'Bottom', jitter: .25},
	
	transDuration: {val: 3000, min: 0, max: 10000, step: 50, name: 'Transition Duration', jitter: .75},
	transEaseType: 'EaseLinearWave',

	delayDuration: {val: 0, min: 0, max: 10000, step: 50, name: 'Transition Delay', jitter: .75},
	delayEaseType: 'EaseLinearWave',
	delayOrder: 'all-at-once',
	
	bandShadow: 'none',
	colorThemeType: 'blackWhite'
};